# Generated by Django 6.0.6 on 2026-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
