# Generated by Django 6.1 on 2026-08-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ano_nascimento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField(blank=True)),
                ('resumo', models.TextField(blank=True)),
                ('nome_editora', models.CharField(blank=True, max_length=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.autor')),
            ],
        ),
    ]
