# Generated by Django 6.1 on 2026-08-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_publicacao',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
