# Generated by Django 6.1 on 2026-08-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_alter_livro_data_publicacao'),
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autor.autor'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
