# Generated by Django 6.0.6 on 2026-06-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='titulo', max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('sinopse', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Filmes',
            },
        ),
    ]
