# Generated by Django 6.0.6 on 2026-06-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.PositiveIntegerField(default=0, help_text='digite uma nota de 0 a 5'),
        ),
    ]
