# Generated by Django 6.0.6 on 2026-06-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título', max_length=100)),
                ('autor', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('prioridade_leitura', models.PositiveIntegerField(help_text='Digite um número de 1 a 5')),
                ('sinopse', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
